### ISSUE TITLE
Not showing keyboard if UIElement IsReadOnly is set to True

### ISSUE THREAD

**Issue by saturne1606** [maximcus/WPFTabTip#23]
Hi!

Can you add this to your wonderfull library?

**Comment by maximcus** [comment]
Hi, I think that this behavior is exactly the one most people would expect. (see #19 )

If for some reason you want to open a keyboard even when your `UIElement` is read-only I would suggest that you should fork this project, and change it to be the way you want, starting with `TabTipAutomation.BindTo<T>()` method. I no longer provide support for this project, because I moved to different things, and no longer even work with WPF.
